export const UPDATE_STATE = "UPDATE_STATE";
export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

export const createUserActionTypes = [
  CREATE_USER,
  CREATE_USER_SUCCESS,
  CREATE_USER_ERROR,
];
