export const INITIAL_APP_SUCCESS = 'INITIAL_APP_SUCCESS';
export const INITIAL_APP = 'INITIAL_AP';
export const INITIAL_APP_ERROR = 'INITIAL_APP_ERROR';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const ADD_FETCHING_TYPE = 'ADD_FETCHING_TYPE';
export const REMOVE_FETCHING_TYPE = 'REMOVE_FETCHING_TYPE';
export const OPEN_GLOBAL_DIALOG = 'OPEN_GLOBAL_DIALOG';
export const CLOSE_GLOBAL_DIALOG = 'CLOSE_GLOBAL_DIALOG';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';

export const initialAppActionTypes = [
  INITIAL_APP,
  INITIAL_APP_SUCCESS,
  INITIAL_APP_ERROR
];
