# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :update_match do
    match(type: "adhoc", app_identifier: ENV["FASTLANE_IOS_APP_ID"])
  end


  desc "deploy firebase uat"
  lane :beta do
    match(type: "adhoc", app_identifier: ENV["FASTLANE_IOS_APP_ID"], readonly: true)

    build_app(
      include_bitcode: true,
      export_method: "ad-hoc",
      scheme: ENV["FASTLANE_IOS_SCHEMA"],
      workspace: ENV["FASTLANE_IOS_WORKSPACE"],
      export_options: {
        provisioningProfiles: { 
          ENV["FASTLANE_IOS_APP_ID"] => ENV["FASTLANE_IOS_APP_PROFILE"],
        }
      })
      firebase_app_distribution(
        app: ENV['FIREBASE_APP_ID'],
        firebase_cli_token: ENV["FIREBASE_TOKEN"],
        groups: ENV['FIREBASE_GROUPS'],
        ipa_path: ENV['IPA_PATH']
      )
  end
end
