# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "deploy testflight"
  lane :beta do
    match(type: "appstore", app_identifier: ENV["FASTLANE_IOS_APP_ID"], readonly: true)

    build_app(
      include_bitcode: true,
      export_method: "app-store",
      scheme: ENV["FASTLANE_IOS_SCHEMA"],
      workspace: ENV["FASTLANE_IOS_WORKSPACE"],
      export_options: {
        provisioningProfiles: { 
          ENV["FASTLANE_IOS_APP_ID"] => ENV["FASTLANE_IOS_APP_PROFILE"],
        }
      })

    upload_to_testflight
  end
end
