# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Deploy to Apple Store Alpha"
  lane :alpha do
    gym(scheme: "foodmate")
    pilot
  end

  desc "Deploy new version to Apple Store"
  lane :release do
    gym(scheme: "foodmate")
    deliver(force: true)
  end

  after_all do |lane|
  end

  error do |lane, exception|
    
  end
end
